version: "3"

networks:
  my-network:

services:

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      my-network:

  bot:
    build:
      context: ./
    container_name: bot
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      my-network:
